# backend/app/services/marcadores_map.py

from typing import Dict

KEY_TO_JINJA_VARIABLE_MAP: Dict[str, str] = {

    # --- CLAVES DE IDENTIFICACIÓN ---
    # De A1 a A23
    "CdS": "A23",
    "make": "A1",
    "type": "A2",
    "variant": "A3",
    "version": "A4",
    "commercial_name": "A5",
    "category": "A6",
    "manufacturer_base_vehicle": "A7",
    "manufacturer_address_line1": "A8",
    "manufacturer_address_line2": "A9",
    "manufacturer_address_line3": "A10",
    "vin": "A11",
    "vin_location": "A12",
    "implication_number": "A13",
    "type_described": "A14",
    "date": "A15",
    "remarks_6_1": "A16",
    "remarks_7_1": "A17",
    "remarks_8": "A18",
    "remarks_11": "A19",
    "alternative_type_1": "A20",
    "alternative_type_2": "A21",
    "alternative_type_3": "A22",

    # --- CLAVES DE DIMENSIONES, MASAS, MOTOR, ETC. ---
    # De B1 a B70
    "axles": "B1",
    "powered_axles": "B2",
    "wheelbase": "B3",
    "axle_track": "B4",
    "length": "B5",
    "width": "B6",
    "height": "B7",
    "rear_overhang": "B8",
    "running_mass": "B9",
    "max_mass": "B10",
    "mass_distribution": "B11",
    "max_axle_mass": "B12",
    "max_roof_load": "B13",
    "max_trailer_mass": "B14",
    "max_combination_mass": "B15",
    "max_coupling_load": "B16",
    "engine_manufacturer": "B17",
    "engine_code": "B18",
    "working_principle": "B19",
    "direct_injection": "B20",
    "pure_electric": "B21",
    "hybrid": "B22",
    "cylinders": "B23",
    "capacity": "B24",
    "fuel": "B25",
    "max_power": "B26",
    "clutch_type": "B27",
    "gearbox_type": "B28",
    "gear": "B29",
    "final_drive_ratio": "B30",
    "tyres_wheels_1": "B31",
    "tyres_wheels_2": "B32",
    "steering_assistance": "B33",
    "braking_system_1": "B34",
    "braking_system_2": "B35",
    "body_type": "B36",
    "vehicle_color": "B37",
    "doors_config": "B38",
    "seats_config": "B39",
    "coupling_approval": "B40",
    "max_speed": "B41",
    "noise_stationary": "B42",
    "noise_drive_by": "B43",
    "emissions_standard": "B44",
    "emissions_exhaust": "B45",
    "co_emissions": "B46",
    "hc_emissions": "B47",
    "nox_emissions": "B48",
    "hc_nox_emissions": "B49",
    "particulates": "B50",
    "smoke_absorption": "B51",
    "co2_combined_nedc": "B52",
    "co2_extra_urban_nedc": "B53",
    "co2_urban_nedc": "B54",
    "fuel_combined_nedc": "B55",
    "fuel_extra_urban_nedc": "B56",
    "fuel_urban_nedc": "B57",
    "co2_combined_wltp": "B58",
    "co2_maximum_value_wltp": "B59",
    "co2_high_wltp": "B60",
    "co2_medium_wltp": "B61",
    "co2_low_wltp": "B62",
    "fuel_combined_wltp": "B63",
    "fuel_maximum_value_wltp": "B64",
    "fuel_high_wltp": "B65",
    "fuel_medium_wltp": "B66",
    "fuel_low_wltp": "B67",
    "power_consumption": "B68",
    "electric_range": "B69",
    "electric_range_city": "B70",
}