# backend/app/services/marcadores_map.py

from typing import Dict

KEY_TO_JINJA_VARIABLE_MAP: Dict[str, str] = {
    "Make": "A1",  
    "Model": "A2",
    "Variant": "A3",

    "Remark_6": "A16", 

    "Number of axles / wheels": "B1",  # [cite: 7]
    "Powered axles": "B2",  # [cite: 7]
    "Wheelbase": "B3",  # [cite: 7]
    "Axle(s) track – 1 / 2": "B4",  # [cite: 7]
    "Length": "B5",  # [cite: 7]
    "Width": "B6",  # [cite: 7]
    "Height": "B7",  # [cite: 7]
    # "Rear overhang": "B8",  # [cite: 7]
    # "Mass of the vehicle with bodywork in running order": "B9",  # [cite: 7]
    # "Technically permissable maximum laden mass": "B10",  # [cite: 7]
    # "Distribution of this mass among the axles – 1 / 2": "B11",  # [cite: 7]
    # "Technically perm. max mass on each axle – 1 / 2": "B12",  # [cite: 7]
    # "Maximum permissible roof load": "B13",  # [cite: 7]
    # "Maximum mass of trailer – braked / unbraked": "B14",  # [cite: 7]
    # "Maximum mass of combination": "B15",  # [cite: 7]
    # "Maximum vertical load at the coupling point for a trailer": "B16",  # [cite: 7]
    # "Engine manufacturer": "B17",  # [cite: 7]
    # "Engine code as marked on the engine": "B18",  # [cite: 7]
    # "Working principle": "B19",  # [cite: 7]
    # "Direct injection": "B20",  # [cite: 7]
    # "Pure electric": "B21",  # [cite: 7]
    # "Hybrid [electric] vehicle": "B22",  # [cite: 7]
    # "Number and arrangement of cylinders": "B23",  # [cite: 7]
    # "Capacity": "B24",  # [cite: 7]
    # "Fuel": "B25",  # [cite: 7]
    # "Maximum net power": "B26",  # [cite: 7]
    # "Clutch (type)": "B27",  # [cite: 7]
    # "Gearbox (type)": "B28",  # [cite: 7]
    # "Gear": "B29",  # [cite: 7]
    # "Final drive ratio": "B30",  # [cite: 8]
    # "Tyres on wheels 1": "B31",  # [cite: 8]
    # "Tyres on wheels 2": "B32",  # [cite: 8]
    # "Steering, method of assistance": "B33",  # [cite: 8]
    # "Brief description of the braking system": "B34",  # [cite: 8]
    # "Brief description of the braking system - Detail": "B35",  # [cite: 8] # As {{B35}} is a continuation without a distinct label in source.
    # "Type of body": "B36",  # [cite: 8]
    # "Colour of vehicle": "B37",  # [cite: 8]
    # "Number and configuration of doors": "B38",  # [cite: 8]
    # "Number and position of seats": "B39",  # [cite: 8]
    # "EC type approval mark of coupling device, if fitted": "B40",  # [cite: 8] # Corrected "couplind" to "coupling"
    # "Maximum speed": "B41",  # [cite: 8]
    # "Sound level - Stationary (dB(A)) at engine speed (min-1)": "B42",  # [cite: 8]
    # "Sound level - Drive-by (dB(A))": "B43",  # [cite: 8]
    # "Emissions standard": "B44",  # [cite: 8]
    # "Exhaust emission": "B45",  # [cite: 8]
    # "CO (g/km)": "B46",  # [cite: 8]
    # "HC (g/km)": "B47",  # [cite: 8]
    # "NOX (g/km)": "B48",  # [cite: 8]
    # "HC+NOX (g/km)": "B49",  # [cite: 8]
    # "Particulates (g/km)": "B50",  # [cite: 8]
    # "Smoke (corrected value of the absorption coefficient)": "B51",  # [cite: 9]
    # "CO2 (g/km) - combined (NEDC)": "B52",  # [cite: 10]
    # "CO2 (g/km) - extra-urban conditions (NEDC)": "B53",  # [cite: 10]
    # "CO2 (g/km) - urban conditions (NEDC)": "B54",  # [cite: 10]
    # "Fuel consumption (l/100km) - combined (NEDC)": "B55",  # [cite: 10]
    # "Fuel consumption (l/100km) - extra-urban conditions (NEDC)": "B56",  # [cite: 10]
    # "Fuel consumption (l/100km) - urban conditions (NEDC)": "B57",  # [cite: 10]
    # "CO2 (g/km) - Combined (WLTP)": "B58",  # [cite: 12]
    # "CO2 (g/km) - Maximum value (WLTP)": "B59",  # [cite: 12]
    # "CO2 (g/km) - High (WLTP)": "B60",  # [cite: 12]
    # "CO2 (g/km) - Medium (WLTP)": "B61",  # [cite: 12]
    # "CO2 (g/km) - Low (WLTP)": "B62",  # [cite: 12]
    # "Fuel consumption (l/100km) - Combined (WLTP)": "B63",  # [cite: 12]
    # "Fuel consumption (l/100km) - Maximum value (WLTP)": "B64",  # [cite: 12]
    # "Fuel consumption (l/100km) - High (WLTP)": "B65",  # [cite: 12]
    # "Fuel consumption (l/100km) - Medium (WLTP)": "B66",  # [cite: 12]
    # "Fuel consumption (l/100km) - Low (WLTP)": "B67",  # [cite: 12]
    # "Power consumption weighted/combined (Pure electric/Hybrid)": "B68",  # [cite: 13]
    # "Electrical range (Pure electric/Hybrid)": "B69",  # [cite: 13]
    # "Electrical range in city (Pure electric/Hybrid)": "B70",  # [cite: 13]
}